sonar.projectKey=opentelemetry-propagator-b3
sonar.sources=src
sonar.tests=tests
sonar.inclusions=src/**/*.os,src/**/*.bsl
sonar.coverageReportPaths=out/genericCoverage.xml
sonar.genericExecution.reportPaths=out/genericExecution.xml
