name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  qa:
    uses: autumn-library/workflows/.github/workflows/sonar.yml@v1
    with:
      github_repository: ${{ github.repository }}
      oscript_version: 2.0.0
      test_engine: oneunit
      test_recursive: true
      coveralls: true
      sonarqube: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
